### ISSUE TITLE
UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.  If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST']

### ISSUE THREAD

**Issue by flycocke** [MiroPsota/torch_packages_builder#3]
after install,tip:UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST']

**Comment by flycocke** [comment]
ubuntu2204,docker ,pytorch2.3.0,cu121

**Comment by MiroPsota** [comment]
I think this is just an irrelevant warning from the Docker image you are using (if you're not compiling anything).

This env variable is not relevant for the users which just download compiled packages from this repository as nothing is compiled in that case. To be clear, the packages from this repository are compiled with `TORCH_CUDA_ARCH_LIST` set to the exact same values as PyTorch uses for different versions when they are compiled.
